src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_updated;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle(string $title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription(string $description)
    {
        $this->description = $description;

        return $this;
    }

    public function getDateUpdated()
    {
        return $this->date_updated;
    }

    /*public function setDateUpdated(DateTimeInterface $date_updated) //не используем т к в конструкторе указываем значение для даты_апдейт
    {
        $this->date_updated = $date_updated;

        return $this;
    }
     */
    
    public function __construct() { //когда создается объект класса запускается в первую очередь конструктор
        $this->date_updated = new \DateTime('now'); //текущее время сохраняем в дату_апдейт
    }
}

src/Controller/AboutContactsController.php
<?php

namespace App\Controller; // app - папка src(с него идет поиск), по неймсейсу система понимает где искать файл

use \Symfony\Bundle\FrameworkBundle\Controller\AbstractController;// as AbstractController; //as можно не писать исполбзуется посл часть пути как имя


class AboutContactsController extends AbstractController
{
    public function contacts()
    {
        return  $this->render('contacts.html.twig');//render функция ищет уже в папке template файл contacts
    }
    public function about()
    {
        return  $this->render('about.html.twig');//render функция ищет уже в папке template файл about
    }
}

src/Controller/AboutController.php
<?php

namespace App\Controller; // app - папка src(с него идет поиск), по неймсейсу система понимает где искать файл

use \Symfony\Bundle\FrameworkBundle\Controller\AbstractController;// as AbstractController; //as можно не писать исполбзуется посл часть пути как имя


class AboutController extends AbstractController
{
    public function index()
    {
        return  $this->render('about.html.twig');//render функция ищет уже в папке template
    }
}

src/Controller/ContactsController.php
<?php

namespace App\Controller; // app - папка src(с него идет поиск), по неймсейсу система понимает где искать файл

use \Symfony\Bundle\FrameworkBundle\Controller\AbstractController;// as AbstractController; //as можно не писать исполбзуется посл часть пути как имя


class ContactsController extends AbstractController
{
    public function index()
    {
        return  $this->render('contacts.html.twig');//render функция ищет уже в папке template
    }
}

src/Controller/HomeController.php
<?php


namespace App\Controller; // app - папка src(с него идет поиск), по неймсейсу система понимает где искать файл

use \Symfony\Bundle\FrameworkBundle\Controller\AbstractController;// as AbstractController; //as можно не писать исполбзуется посл часть пути как имя

class HomeController extends AbstractController
{
    public function index()
    {
        return  $this->render('home.html.twig');//render функция ищет уже в папке template
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller; // app - папка src(с него идет поиск), по неймсейсу система понимает где искать файл

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;// as AbstractController; //as можно не писать исполбзуется посл часть пути как имя
use Symfony\Component\HttpFoundation\Request; //добавляем чтобы работать с реквестами,  алиасаом будет посл слово пути (тут Реквест)
use App\Entity\News;


class NewsController extends AbstractController
{
    public function showList()  //будет выводить список новостей
    {
        $em = $this->getDoctrine()->getManager();
        $NewsRepo = $em->getRepository(News::class); //    \неймспейс из шапки файла
        
        
        $news_list = $NewsRepo->getNews();
        
        //dump($news); //аналог вардампа в пхп
        
        return  $this->render('news/list.html.twig', [
            'news_list' => $news_list
        ]);//render функция ищет уже в папке template
    }
    
    public function add(Request $req) //добавляем еще ответ, в аргументы передаем объект из подключаемого класса 
    {
        //var_dump($req->request->all()); //запрашиваем все( all(); ) параметры из обьекта request из переменной req
        if($req->isMethod('POST'))
        {
            $data = $req->request->all(); //в дату попадает запрос
            
            $em = $this->getDoctrine()->getManager();
            
            $NewsRepo = $em->getRepository(News::class); //    \неймспейс из шапки файла
            
            
            try {
                //помещаем код который может вызвать в ошибку в трай
                $NewsRepo->addNews($data); // передаем данные в невсРепозиторий 
               
            } catch (\Doctrine\DBAL\DBALException $ex) {
                var_dump("Error");
                return $this->render('news/exists.html.twig');
            }
             
            /*
            $em = $this->getDoctrine()->getManager(); //получение обьекта по работе с базой данных
            
            $News = new \App\Entity\News(); //создаем экземляр обьекта класса News 
            
            
            //задаем параметры новости
            $News->setTitle($data['title']);
            $News->setDescription($data['description']);
            //дату добавления в классе News.php
            
            
            $em->persist($News);// подготавливает запрос
            $em->flush(); //создаем транзу для запросов
            */
            
            return  $this->render('news/success.html.twig'); //возвращаем страницу успеха
        }
        return $this->render('news/add.html.twig',[
            'title' => ''
        ]);
    }
    
    public function show($id) //аналог функции add 
    { 
        
        $em = $this->getDoctrine()->getManager(); //entity manager может вытаскивать по одной строке по айди

        $News = $em->find(News::class, $id);
        
        //dump($News); //die;
        
        return $this->render('news/show.html.twig', [
            'News' => $News
        ]);
    }
    public function deleteNews($id) //аналог функции add 
    { 
        
        $em = $this->getDoctrine()->getManager(); //entity manager может вытаскивать по одной строке по айди

        $News = $em->find(News::class, $id);
        
        $title = $News->getTitle();
        
        $em->remove($News);
        
        $em->flush();
        
        //dump($News); //die;
        
        return $this->render('news/delete.html.twig', [
            'title' => $title
        ]);
    }
    
}

templates/about.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>About us</h1>
    <p>Building a website is, in many ways, an exercise of willpower. It’s tempting to get distracted by the bells and whistles of the design process, and forget all about creating compelling content.</p>
    <p>It's that compelling content that's crucial to making inbound marketing work for your business.</p>
    <p>So how do you balance your remarkable content creation with your web design needs? It all starts with the "About Us" page.</p>
    <p>For a remarkable about page, all you need to do is figure out your company's unique identity, and then share it with the world. Easy, right? Of course not. Your "About Us" page is one of the most important pages on your website, and it needs to be well crafted. This profile also happens to be one of the most commonly overlooked pages, which is why you should make it stand out.</p>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Blog news{% endblock %}</title>
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/style.css" />
        <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
        <script src="/jquery-3.3.1.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script defer src="/main.js"></script>
    {% block stylesheets %}{% endblock %}
</head>
<body class="container">
    <header class="main-border">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand d-lg-none" href="#">Menu</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{path('home')}}">Home</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{path('contacts')}}">Contacts</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{path('about')}}">About us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{path('newsList')}}">News</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="page main-border">
    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/contacts.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6 pb-5">
            <form action="mail.php" method="post">
                <div class="card border-primary main-radius">
                    <div class="card-header p-0 contact-form">
                        <div class="bg-info text-white text-center py-3 contact-form">
                            <h3><i class="fa fa-envelope"></i> Contact form</h3>
                        </div>
                    </div>
                    <div class="card-body p-3">
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                </div>
                                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Name" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                                </div>
                                <input type="email" class="form-control" id="nombre" name="email" placeholder="Email" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                                </div>
                                <textarea class="form-control" placeholder="Message" required></textarea>
                            </div>
                        </div>
                        <div class="text-center">
                            <input type="submit" value="Send" class="btn btn-info btn-block py-2 main-radius">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Home</h1>
{% endblock %}

templates/news/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Add news</h1>
    <form action="{{path('addNews')}}" method="POST">
        <div class="form-group">
            <label for="title">Title</label>
            <input name="title" type="text" class="form-control" id="title">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea name="description" class="form-control" id="description" rows="6" ></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-success">Add news</button>
        </div>
    </form>

{% endblock %}

templates/news/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a class="mb-3" href="{{path('newsList')}}"><i class="fa fa-arrow-left" aria-hidden="true"></i> News</a>
    <h1 class="delete-news">News "<span>{{title}}</span>" removed success</h1>
{% endblock %}

templates/news/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Edit news</h1>
{% endblock %}

templates/news/exists.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h2>News already exists!!</h2>
<a class="btn btn-primary" href="{{path('newsList')}}">News</span></a>
{% endblock %}

templates/news/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="d-flex align-items-center">
    <h1>News list</h1>
    <a class="btn btn-primary ml-3" href="{{path('addNews')}}">Add news</a>
    </div>
    <div class="news-list row">
        {% for news in news_list %}
            <div class="col-sm-12">
                <div class="row oneNews">
                    <h3 class="col-sm-9 mb-3 mt-3">{{news.title}}</h3>
                    <div class="col-sm-3 mt-3 data-news">{{news.dateUpdated|date("h:i d/m/Y")}}</div>
                    <div class="col-sm-12 news">
                        {{news.description|slice(0, 350)}}...
                        <a href="{{path('showNews', {'id':news.id}) }}" class="">Read more</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row pt-3 pb-3">
        <div class="col-9 ret-back">
            <a href="{{path('newsList')}}"><i class="fa fa-arrow-left" aria-hidden="true"></i> News</a>
        </div>
        <div class="col-3">
            <div class="data-news">{{News.dateUpdated|date("h:i d/m/Y")}}</div>
        </div>
    </div>
    <h1 class="news-title">{{News.title}}</h1>
    <div class="news-desk pb-5">
        <p>{{News.description}}</p>
    </div>
    
    
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteNews">
        Delete news
    </button>
    <div class="modal fade" id="deleteNews" tabindex="-1" role="dialog" aria-labelledby="deleteNewsLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteNews">Warning</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Delete news:</p>
                    <b>{{News.title}}</b>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <a type="button" class="btn btn-primary" href="{{path('deleteNews', {'id':News.id}) }}">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/news/success.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<a class="mb-3" href="{{path('newsList')}}"><i class="fa fa-arrow-left" aria-hidden="true"></i> News</a>
<h2>News created success</h2>
<a class="btn btn-primary" href="{{path('newsList')}}">News</span></a>
<a class="btn btn-primary" href="{{path('addNews')}}">Add more</span></a>
{% endblock %}